import React from "react";
import { View, Text, Pressable, StyleSheet, TextInput, ViewStyle } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { colors } from "../theme/colors";
import { spacing, radius } from "../theme/spacing";

export function Screen({ children, dark=false, style }: { children: React.ReactNode; dark?: boolean; style?: ViewStyle }) { return <View style={[styles.screen, dark && styles.dark, style]}>{children}</View>; }
export function Header({ title, onBack, right, onMenu, onRightPress }: { title: string; onBack?:()=>void; right?:React.ReactNode; onMenu?:()=>void; onRightPress?:()=>void }) { return <View style={styles.header}>{onBack ? <Pressable onPress={onBack} style={styles.icon}><Ionicons name="chevron-back" size={25} color={colors.textPrimary}/></Pressable> : <Pressable onPress={onMenu} style={styles.icon}><Ionicons name="menu-outline" size={23} color={colors.textPrimary}/></Pressable>}<Text style={styles.headerTitle}>{title}</Text><Pressable onPress={onRightPress} style={styles.headerRight}>{right || <Ionicons name="notifications-outline" size={22} color={colors.textPrimary}/>}</Pressable></View>; }
export function Avatar({ initial, size=38 }: { initial:string; size?:number }) { return <View style={[styles.avatar,{width:size,height:size,borderRadius:size/2}]}><Text style={styles.avatarText}>{initial}</Text></View>; }
export function PrimaryButton({ title, onPress, light=false, style }: { title:string; onPress?:()=>void; light?:boolean; style?:ViewStyle }) { return <Pressable onPress={onPress} style={[styles.button, light && styles.lightButton, style]}><Text style={[styles.buttonText,light&&styles.darkText]}>{title}</Text></Pressable>; }
export function Section({ title, action, onAction }: { title:string; action?:string; onAction?:()=>void }) { return <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>{title}</Text>{action&&<Pressable onPress={onAction}><Text style={styles.action}>{action}</Text></Pressable>}</View>; }
export function Segmented({ values, selected, onSelect }: { values:string[]; selected:string; onSelect:(v:string)=>void }) { return <View style={styles.segmented}>{values.map(v=><Pressable key={v} onPress={()=>onSelect(v)} style={[styles.segment,selected===v&&styles.segmentSelected]}><Text style={[styles.segmentText,selected===v&&styles.segmentSelectedText]}>{v}</Text></Pressable>)}</View>; }
export function SearchBox({ value, onChangeText }: { value:string; onChangeText:(v:string)=>void }) { return <View style={styles.search}><Ionicons name="search" size={18} color={colors.textSecondary}/><TextInput value={value} onChangeText={onChangeText} placeholder="Search groups" placeholderTextColor={colors.textMuted} style={styles.searchInput}/></View>; }
export const styles=StyleSheet.create({ screen:{flex:1,backgroundColor:colors.background,paddingHorizontal:20},dark:{backgroundColor:colors.primary},header:{height:62,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},headerTitle:{fontSize:20,fontWeight:"700",color:colors.textPrimary},headerRight:{width:30,alignItems:"flex-end"},icon:{width:36},avatar:{backgroundColor:"#D7D7D7",alignItems:"center",justifyContent:"center"},avatarText:{fontSize:15,fontWeight:"700",color:colors.textPrimary},button:{height:48,borderRadius:radius.md,backgroundColor:colors.primary,alignItems:"center",justifyContent:"center",paddingHorizontal:20},lightButton:{backgroundColor:colors.surface},buttonText:{color:colors.selectedText,fontSize:14,fontWeight:"700"},darkText:{color:colors.primary},sectionHeader:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginBottom:12},sectionTitle:{fontSize:16,fontWeight:"700",color:colors.textPrimary},action:{fontSize:12,fontWeight:"600",color:colors.textPrimary},segmented:{flexDirection:"row",gap:8},segment:{paddingHorizontal:16,height:34,borderRadius:20,justifyContent:"center",backgroundColor:"#F1F1F1"},segmentSelected:{backgroundColor:colors.primary},segmentText:{fontSize:12,fontWeight:"600",color:colors.textPrimary},segmentSelectedText:{color:colors.selectedText},search:{height:42,borderRadius:10,backgroundColor:colors.inputBackground,flexDirection:"row",alignItems:"center",paddingHorizontal:12,gap:8},searchInput:{flex:1,fontSize:13,color:colors.textPrimary}});
